In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("expr_degs.csv",sep=",", index_col =0)
df

,201540_at,202565_s_at,206310_at,212385_at,226382_at,240766_at,risk,Status,Time
GSM158713.CEL.gz,9.271564,9.972121,12.107772,10.098923,9.322235,9.661355,1,1,218
GSM158724.CEL.gz,10.188306,9.564933,12.807724,10.079383,9.621344,10.505519,1,1,302
GSM158726.CEL.gz,9.926397,8.081620,7.940338,10.037833,8.373142,11.586075,1,1,13
GSM158739.CEL.gz,9.377725,9.464197,11.854034,9.348862,8.267016,6.932307,1,1,248
GSM158762.CEL.gz,9.695357,8.788698,11.187703,8.793689,7.944234,8.336559,1,1,44
...,...,...,...,...,...,...,...,...,...
GSM159034.CEL.gz,7.990120,8.490336,8.959715,8.267766,7.208349,9.595645,0,0,4893
GSM159035.CEL.gz,8.326087,7.912357,9.044203,7.704476,7.673850,6.412768,0,0,4149
GSM159078.CEL.gz,9.205484,9.257929,9.552739,7.110434,8.370277,6.241038,0,0,5151
GSM159090.CEL.gz,7.923169,6.517957,9.138377,7.380715,6.994545,7.363956,0,0,4479
GSM159094.CEL.gz,10.277935,7.240839,7.065529,7.541894,6.399648,6.277156,0,0,3885

In [10]:
df2 = pd.read_csv("result1_glmnet_coeficent-29-6.csv",sep =",")
df2

           name  coefficient
0    X201540_at     0.181780
1  X202565_s_at     0.072761
2    X206310_at     0.050001
3  X221942_s_at     0.020330
4    X240766_at     0.016465

In [11]:
%pwd

'/home/nasr/Desktop/my_project2_adult/intermediate/geo_data/Kaplan meier plot/> 30 day/202540_at FHL1'

In [12]:
df2 = df["201540_at"]
df2.to_csv("201540_at_expression.csv", sep=",")
df2 = pd.read_csv("201540_at_expression.csv", sep=",")

In [18]:
#df2["FHL1"] = 0.0779963840089317 * df2["FHL1"]
#df["SPNS3"] = 0.0507993060658612 * df["SPNS3"]
df2["201540_at"] = 0.181780 * df2["201540_at"]
#df["ADD2"] =-0.000713971400327776 * df["ADD2"]
#df["KCNMB4"] = -0.0311212288312401 * df["KCNMB4"] 
df2

          Unnamed: 0  201540_at
0   GSM158713.CEL.gz   0.306369
1   GSM158724.CEL.gz   0.336662
2   GSM158726.CEL.gz   0.328008
3   GSM158739.CEL.gz   0.309877
4   GSM158762.CEL.gz   0.320373
..               ...        ...
92  GSM159034.CEL.gz   0.264025
93  GSM159035.CEL.gz   0.275127
94  GSM159078.CEL.gz   0.304186
95  GSM159090.CEL.gz   0.261813
96  GSM159094.CEL.gz   0.339624

[97 rows x 2 columns]

In [14]:
df2.to_csv("expr_coefficient_201540_at.csv", sep=",")

In [15]:
df3 =pd.read_csv("expr_coefficient_201540_at.csv", sep=",")
df3 =df3.set_index("sample")
df3

                  201540_at
sample
GSM158713.CEL.gz   1.685385
GSM158724.CEL.gz   1.852030
GSM158726.CEL.gz   1.804420
GSM158739.CEL.gz   1.704683
GSM158762.CEL.gz   1.762422
...                     ...
GSM159034.CEL.gz   1.452444
GSM159035.CEL.gz   1.513516
GSM159078.CEL.gz   1.673373
GSM159090.CEL.gz   1.440274
GSM159094.CEL.gz   1.868323

[97 rows x 1 columns]

In [16]:
df3["score"] = df3.sum(axis=1)
df3

                  201540_at     score
sample
GSM158713.CEL.gz   1.685385  1.685385
GSM158724.CEL.gz   1.852030  1.852030
GSM158726.CEL.gz   1.804420  1.804420
GSM158739.CEL.gz   1.704683  1.704683
GSM158762.CEL.gz   1.762422  1.762422
...                     ...       ...
GSM159034.CEL.gz   1.452444  1.452444
GSM159035.CEL.gz   1.513516  1.513516
GSM159078.CEL.gz   1.673373  1.673373
GSM159090.CEL.gz   1.440274  1.440274
GSM159094.CEL.gz   1.868323  1.868323

[97 rows x 2 columns]

In [29]:
df3['score'].median()

1.65592975911709

In [34]:
df3['Expression'] = df3['score'] > 1.6

In [35]:
df3 =df3*1

In [36]:
df3

                  201540_at     score  low_high  Expression
sample
GSM158713.CEL.gz   1.685385  1.685385         0           1
GSM158724.CEL.gz   1.852030  1.852030         1           1
GSM158726.CEL.gz   1.804420  1.804420         1           1
GSM158739.CEL.gz   1.704683  1.704683         1           1
GSM158762.CEL.gz   1.762422  1.762422         1           1
...                     ...       ...       ...         ...
GSM159034.CEL.gz   1.452444  1.452444         0           0
GSM159035.CEL.gz   1.513516  1.513516         0           0
GSM159078.CEL.gz   1.673373  1.673373         0           1
GSM159090.CEL.gz   1.440274  1.440274         0           0
GSM159094.CEL.gz   1.868323  1.868323         1           1

[97 rows x 4 columns]

In [33]:
df3.to_csv("km_201540_at.csv", sep=",")